name: "Product Feature Section"
tags:
  - feature
  - content
  - icons
  - product
  - layout
  - grid
  - flexbox
  - ecommerce
  - sales
category: containers
description: Feature sections to show off or detail how awesome your product is. On smaller screens, icons shift above the text to fit nicely.
versions:
  - 6.3.0
  - 6.3.1
author:
  github: rafibomb
  name: Rafi
containerClass: none
